### PR TITLE
Partial Support for Segwit Programs

### PR DESCRIPTION
**Pull request by jc23424**
This makes the interpreter aware enough to evaluate segwit programs without full segwit support
Similar to P2SH support - segwit P2WPKH and P2WSH are new templated script types. Instead of including signatures in the witness as in bitcoin, the scriptsig is modified to also contain the contents of the witness (specifically, the scriptSig is prepended with what would have appeared in the witness)

For example, a bitcoin redeem of a P2WPKH looks like
```
witness: <sig> <pubkey>
scriptSig: (empty)
scriptPubKey: OP_0 <20 byte pubkeyhash>
```

to redeem a P2WPKH output on the BTCP blockchain post fork:
```
witness: (n/a, does not exist)
scriptSig: <sig> <pubkey>
scriptPubKey: OP_0 <20 byte pubkeyhash>
```

The case for P2WSH (as well as the P2SH wrapped analogues of these) are similar. For example P2SH(P2WSH)
```
witness: (n/a)
scriptSig: <sigs...> <script> <OP_0 <sha256(<script>)>>
scriptPubKey: OP_HASH160 <hash160(OP_0 <sha256(<script>)>)> OP_EQUAL
```

The primary goal is to allow BTC holders with segwit UTXOs to unlock their outputs. As such, sending to segwit addresses is still a non-standard transaction, but segwit outputs may be spent.

A couple of notes here:
- the signature serialization method is still old-style
- at a later date, full-segwit can be soft forked in, because of the signature serialization (mentioned above) care will have to be taken - easiest way is to soft-fork in full segwit (w/ new signature serialization) starting with witness program version 1)
- this does not address any of the tx malleability issues that full segwit will later address

### CODE REVIEW

**Comment by floreslorca** [comment]
maybe we should bring some segwit related tests from btc, at least to tests the scripts.

**Comment by jc23424** [comment]
yes - that's on my todo list - would be great if you could help!

**Comment by grzegorzszczecin** [comment]
I'm unable to redeem a P2WPKH-P2SH output on the BTCP blockchain.

Error message: Script evaluated without error but finished with a false/empty top stack

**Comment by Ayms** [comment]
Then, what is the method finally? I have tried some combination as I described in #140 without success, and I don't get the above description, the 00 in the segwit address is not an OP_0

**Comment by BlueSilver22** [comment]
@Ayms We plan on rolling out full SegWit support via a BIP9 soft fork in the near future. You should theoretically be able to claim this way but if you can be patient, you could wait until claiming is possible with Electrum.

**Comment by Ayms** [comment]
@BlueSilver22 good news, because as I wrote before forking something that has segwit activated with only a partial support looks quite strange

I am patient (and it's not for me in fact but for my tool, it's a bit tiring to have to solve every specific situation manually) but I am afraid that some others are not, some "rumors" are now surfacing about this now when everybody is trying to move their coins.

What is the theoretical method? Example of raw tx (even theoretical)? I have some live examples to try it at least if you clarify it, again what is written above looks wrong (00 is the witness version not an OP_0)

**Comment by BlueSilver22** [comment]
@ayms the reason there is partial SegWit support is to allow for eventual claiming of SegWit BTC as well as enabling a soft fork (as opposed to a hard fork) for full SegWit support in the near future. There was not enough time to implement it fully before the hard fork. It’s not quite there yet; regardless the other BTC forks don’t support SegWit at all so we believe this is a major improvement over them.

**Comment by BlueSilver22** [comment]
As for the actual code, you will have to speak with @jc23424 as he is the expert here.

**Comment by Ayms** [comment]
@BlueSilver22 I know for the claiming, but most of the BTC forks (regardless of whether they are serious or not, see https://github.com/Ayms/bitcoin-transactions#forked-coins) support segwit, because they just took the bitcoin core code and forked after segwit activation, except those that explicitely said that they will not support it and that logically forked before segwit activation (or used old code), you took the zcl/zec code where segwit was not implemented...

@jc23423 you can answer here or email me if you prefer to check/test the theoretical approach

**Comment by delaredlibre** [comment]
I am waiting for the development team allow me to claim my BTCP through a BTC Segwit P2SH private key.

**Comment by holuan** [comment]
@jc23424 - Hi I tried claiming the coins from my segwit address. After numerous tries I managed to identify my txid and bitcoin private addresses but when I am trying to broadcast my claiming tx on https://explorer.btcprivate.org/tx/send i get the following error:  `An error occured:
16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element). Code:-26`

**Pull request merged**
