### PR TITLE
Replay Protection Fixup

### PR DESCRIPTION
**Pull request by zanethomas**
Modified interpreter.cpp and .h to use replay protection method from
BTCGPU.

Disable bip148 until segwit implementing

Including data missing from previous commit

Updated Tests

Regenerated sighash test data and fixed a couple minor issues in tests.

Added Replay Protection Tests

In Interpeter.cpp::SignatureHash, interpreter.h, and script_tests.cpp I
added closely related segwit code which is currently *not* compiling. I
did this now so that later implementation of segwit will not require
discovering and adding what’s missing and could have been easily
included at this time.

Removed Test Data Generation

Forgot to comment UPDATE_JSON_TESTS out of existence.

### CODE REVIEW

**Comment by jc23424** [comment]
lets leave the segwit code out - its going to be harder to merge later if part of it is merged now
could you please link the relevant BTCGPU code you modeled off of

**Comment by zanethomas** [comment]
ok, will do

**Comment by zanethomas** [comment]
Hold on this, I may need to add a fix.

**Comment by jc23424** [comment]
NACK - CheckBlock is called in places where block height is not known (e.g. in IBD when blocks are not necessarily downloaded in order)

**Pull request closed without merging**
