### PR TITLE
Add ability to force a difficulty bomb

### PR DESCRIPTION
**Pull request by jc23424**

### CODE REVIEW

**Comment by mattpass** [comment]
Is difficulty bomb usage really part of the future plans for BTCP?

**Comment by jc23424** [comment]
This is ready for review now - please review

**Comment by zanethomas** [comment]
Please excuse my ignorance, but what purpose does this serve?

**Comment by aguilaair** [comment]
@zanethomas this allows BTCP to stop the creation of two chains by making one of the chains unusable (stops the creation of 'BTCP calssic' in case of a hard fork(rebase))

**Pull request merged**
