### PR TITLE
Experiment with re-enabling accounts

### PR DESCRIPTION
**Pull request by jc23424**

### CODE REVIEW

**Comment by interbiznw** [comment]
Built and seems to work good so far for me, Will be doing more testing with accounts and the addresses generated for each account soon

**Comment by interbiznw** [comment]
Further testing has went well, No issues found around re-enabling accounts

**Comment by izgzhen** [comment]
Hello, I was curious why accounts are not supported here? What is the rationale?

**Comment by Mrwh0** [comment]
internal node accounting

**Comment by jc23424** [comment]
Accounts weren't supported in the original zcash codebase because of the extra work required to get them working with shielded balances. Also, accounts were never really fully fleshed out in the bitcoin reference implementation.

In the 0.17 release of bitcoin, accounts will be deprecated and eventually fully removed. This branch is available here because a couple of payment processors / merchant integrations rely on accounts, but it will probably NOT be officially merged.

**Comment by Pega88** [comment]
referenced in https://github.com/GENERALBYTESCOM/batm_public/pull/73, as required by BATM. Otherwise whole account logic would need to be manually implemented in BATM to make sure to be able to make payments (i.e. look up UTXO, combine UTXO until amount is reached, or manual sweep all change addresses back to 1 main address). Using accounts would very much avoid this

**Pull request merged**
