### PR TITLE
Deactivate POW Difficulty Bomb

### PR DESCRIPTION
**Pull request by SnippleRifsky**
Commented out all instances of the PowDiffBomb

### CODE REVIEW

**Comment by mattpass** [comment]
Seems to have removed all traces of bomb value setting and implementation, seems good to me. I assume you generated to 600,000+ and it didn't kick in as a super safety check @SnippleRifsky?

Just need someone else to confirm on this also, or I'll check too but looks spot on.

**Comment by dskjkljdas** [comment]
concur

**Comment by mattpass** [comment]
Great, so 3 of us confirming the code looks fine, just need a couple of people to confirm it's tested. Should be absolutely fine, but you don't know till you've tested.

**Comment by bigdaveakers** [comment]
Make that 4, although I like coding standards and therefore like curly braces in my IFs. However, refactoring the entire codebase to some standards to satisfy mild OCD is probably never going to happen!

**Comment by SnippleRifsky** [comment]
Generated blocks on a local node in -regtest to the specified blockheight for the PoWDifficultyBomb.
Once this blockheight was surpassed, the difficulty had no change indicating the removal of the PoWDifficultyBomb was a success.

**Comment by bigdaveakers** [comment]
Need to check deprecation.cpp and deprecation.h  as there is an additional limit set at 800,000

Could do with alignment as this reminds of an upcoming deprecation

**Pull request merged**
